AWSTemplateFormatVersion: "2010-09-09"
Description: This is a CloudFormation Template for RDS mysql with multi az enabled

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "RDS SETUP CONFIGURATION"
        Parameters:
          - DBName
          - DBInstanceClass
          - InitialDBName
          - DeleteProtection 
      - Label:
          default: "DATABASE CONFIGURATION"
        Parameters:
          - StorageCapacity
          - EngineType
          - EngineVersion
          - MasterUsername
          - MasterUserPassword
          - MaxAllocatedStorage
      - Label:
          default: "BACKUP"
        Parameters:
          - BackupRetentionPeriod

Parameters:
  DBName: 
    Description: Enter the Name of the Database
    Type: String
    Default: Mysql-rds

  InitialDBName: 
    Description: Please Enter Initial Database Name 
    Type: String
    Default: wordpress

  DBInstanceClass: 
    Description: Enter the DB instance class
    Type: String
    Default: db.t3.micro
    
  StorageCapacity: 
    Description: Enter the size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
    Default: 20

  BackupRetentionPeriod: 
    Description: Enter the time period for which you want to reten backup
    Type: String
    Default: 1

  DeleteProtection: 
    Description: delete protection T/F
    Type: String
    Default: false
  EngineType: 
    Description: Enter the Engine Type of DB
    Type: String
    Default: mysql
  EngineVersion: 
    Description: Enter the Engine Version of DB
    Type: String
    Default: 8.0.28
    
  MasterUsername: 
    Description:  Enter the Username for MySQL database access
    Type: String
    Default: Admin
    
  MasterUserPassword: 
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: must contain only alphanumeric characters.
  
  MaxAllocatedStorage: 
    Description: Maximum storage capacity on scaling
    Type: Number
    Default: 500


Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnet group for rds
      DBSubnetGroupName: Private-SubnetGroup
      SubnetIds:
        - !ImportValue PrivateSubnet-1
        - !ImportValue PrivateSubnet-2
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PrivateSubnetGroup
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref InitialDBName
      DBInstanceIdentifier: !Ref DBName
      AllocatedStorage: !Ref StorageCapacity 
      DBInstanceClass: !Ref DBInstanceClass 
      StorageType: gp2 
      Engine: !Ref EngineType 
      EngineVersion: !Ref EngineVersion 
      MasterUsername: !Ref MasterUsername 
      MasterUserPassword: !Ref MasterUserPassword 
      MaxAllocatedStorage: !Ref MaxAllocatedStorage 
      MultiAZ: true
      Port: "3306"
      PubliclyAccessible: false
      DeleteAutomatedBackups: true
      DeletionProtection: !Ref DeleteProtection
      BackupRetentionPeriod: !Ref BackupRetentionPeriod 
      CopyTagsToSnapshot: true
      EnableCloudwatchLogsExports: 
        - audit
        - error
        - general
      Tags: 
        - Key: Name
          Value: !Join ['-', [!Ref "AWS::StackName", !Ref "DBName" ]] 
      UseDefaultProcessorFeatures: true
      DBSubnetGroupName: !Ref DBSubnetGroup

Outputs:
  RDSHost:
    Description: The URL of the RDS
    Value: !GetAtt [RDS, Endpoint.Address]
    Export:
      Name: DB-HOST

  RDSName:
    Description: The URL of the RDS
    Value: !Ref InitialDBName
    Export:
      Name: DB-NAME

  RDSUser:
    Description: The URL of the RDS
    Value: !Ref MasterUsername
    Export:
      Name: DB-USER

  RDSPasswd:
    Description: The URL of the RDS
    Value: !Ref MasterUserPassword
    Export:
      Name: DB-PASSWD 
